export const tweetsData = [   
    {
        handle: `@TrollBot66756542 💎`,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Morbi mollis, ipsum nec bibendum tempor, orci arcu pellentesque tellus, at suscipit lacus leo non nisi. Aenean pellentesque metus quis hendrerit egestas.`,
        replies: [],
        isLiked: false,
        isDeleted: false,
        isRetweeted: false,
        isDeleted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },
    {
        handle: `@542t346 `,
        profilePic: `images/no-picture.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Phasellus lectus diam, ultricies ut commodo feugiat, luctus eu elit.`,
        replies: [],
        isLiked: false,
        isDeleted: false,
        isRetweeted: false,
        isDeleted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },
    {
        handle: `@756542`,
        profilePic: `images/no-picture.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Ipsum veniam nulla sunt dolor tempor. Ullamco consectetur dolore id occaecat consectetur sit quis ea duis laborum.`,
        replies: [],
        isLiked: false,
        isDeleted: false,
        isRetweeted: false,
        isDeleted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },    
    {
        handle: `@Elon ✅`,
        profilePic: `images/musk.png`,
        picture: ``,
        likes: 6500,
        retweets: 234,
        tweetText: `In nec felis nec quam ultricies accumsan.`,
        replies: [
                  {
                handle: `@TomCruise ✅`,
                profilePic: `images/tcruise.png`,
                tweetText: `Phasellus metus leo, dignissim quis massa vitae, molestie porttitor justo. `,
            },
                  {
                handle: `@ChuckNorris ✅`,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: ` Ut rhoncus finibus lorem ut luctus. `,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        isDeleted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
        {
        handle: `@NoobCoder12`,
        profilePic: `images/flower.png`,
        likes: 10,
        retweets: 3,
        tweetText: `Suspendisse sed ultrices turpis.`,
        replies: [
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/overflow.png`,
                tweetText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: ` Fusce id euismod erat. Vivamus sed tempus dui.`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        isDeleted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },     
]